#!/bin/bash
# Build per-student arena-byoc binary with baked credentials.
# Used by arena-manager API to generate downloads on-demand.
#
# SECURITY:
#   - The WireGuard private key MUST NOT appear in argv anywhere — argv is
#     world-readable via /proc/<pid>/cmdline. The previous implementation
#     used `go build -ldflags "-X main.privKeyB64=$PRIV ..."`, which leaked
#     the key into go's cmdline.
#   - Fix: priv is read from stdin, then written into a generated Go source
#     file (client/_creds_gen.go) which sets package-level vars in func init().
#     `go build` is invoked with no secrets in argv.
#   - Any stderr from go is scrubbed for the priv key before being forwarded
#     to the caller (defense in depth, in case go ever echoes source).
#
# Usage:
#   echo -n "<priv-b64>" | ./build.sh <server-pub-b64> <tunnel-ip> <server-host> <goos> <goarch> <out>
#
# Example:
#   echo -n "yA5R..." | ./build.sh "aRd6..." 10.201.0.5 wg-byoc.adversario.cl linux amd64 /tmp/arena-byoc

set -euo pipefail

if [ "$#" -ne 6 ]; then
    echo "build.sh: expected 6 args (server-pub-b64 tunnel-ip server-host goos goarch out), priv key read from stdin" >&2
    exit 64
fi

SRV_PUB="$1"
TUN_IP="$2"
SRV_HOST="$3"
GOOS_="$4"
GOARCH_="$5"
OUT="$6"

# Slurp priv key from stdin (no positional arg → not visible in /proc/<pid>/cmdline).
PRIV="$(cat)"
PRIV="${PRIV%$'\n'}"
PRIV="${PRIV%$'\r'}"

if [ -z "$PRIV" ]; then
    echo "build.sh: empty priv key on stdin" >&2
    exit 65
fi

CLIENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/client" && pwd)"

# Basic shape validation on the b64 inputs so we don't paste hostile chars into Go source.
# Allow standard b64 (A-Za-z0-9+/=) and the host/IP charset for the others.
b64_ok() { [[ "$1" =~ ^[A-Za-z0-9+/=]+$ ]]; }
host_ok() { [[ "$1" =~ ^[A-Za-z0-9._:-]+$ ]]; }

if ! b64_ok "$PRIV"; then
    echo "build.sh: priv key not base64-shaped" >&2
    exit 66
fi
if ! b64_ok "$SRV_PUB"; then
    echo "build.sh: server pub key not base64-shaped" >&2
    exit 66
fi
if ! host_ok "$TUN_IP" || ! host_ok "$SRV_HOST"; then
    echo "build.sh: tunnel ip / server host has unexpected chars" >&2
    exit 66
fi

# Per-build temp dir for the generated creds source file. We refuse to overwrite
# someone else's creds file mid-build by giving each build its own working tree.
WORKDIR="$(mktemp -d -t arena-byoc-build-XXXXXX)"
GEN_DIR="$WORKDIR/client"
trap 'rm -rf "$WORKDIR"' EXIT

# Snapshot the client/ tree into the workdir (cheap — main.go + go.mod + go.sum).
cp -a "$CLIENT_DIR/." "$GEN_DIR/"

# Generate the creds file. The vars are declared at package level in main.go;
# init() in the same package can assign to them.
# NOTE: file MUST NOT start with `_` or `.` — go's build system ignores those.
GEN_FILE="$GEN_DIR/zz_creds_gen.go"
cat > "$GEN_FILE" <<EOF
// Code generated by build.sh. DO NOT EDIT — DO NOT COMMIT.
// Contains per-student WG credentials baked at build time.

package main

func init() {
    privKeyB64      = "$PRIV"
    serverPubKeyB64 = "$SRV_PUB"
    tunnelIP        = "$TUN_IP"
    serverHost      = "$SRV_HOST"
}
EOF
chmod 0600 "$GEN_FILE"

# Capture stderr so we can scrub it for the priv key before re-emitting.
TMPERR="$(mktemp)"
# Stack cleanup atop the WORKDIR trap.
trap 'rm -f "$TMPERR"; rm -rf "$WORKDIR"' EXIT

cd "$GEN_DIR"
set +e
CGO_ENABLED=0 GOOS="$GOOS_" GOARCH="$GOARCH_" \
    go build -trimpath -ldflags="-s -w" -o "$OUT" ./... 2>"$TMPERR"
rc=$?
set -e

# Scrub priv key from any go output before forwarding.
if [ -s "$TMPERR" ]; then
    sed "s|$PRIV|<REDACTED_PRIV>|g" "$TMPERR" >&2
fi

if [ "$rc" -ne 0 ]; then
    exit "$rc"
fi

echo "Built: $OUT ($GOOS_/$GOARCH_)"
